package MpsLanguage.actions;

/*Generated by MPS */

import jetbrains.mps.openapi.actions.descriptor.NodeFactory;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.model.SModel;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class ShowConstraintsOnCreateSemanticDomain {
  public static class NodeFactory_3975302705257175528 implements NodeFactory {
    public void setup(SNode newNode, SNode sampleNode, SNode enclosingNode, int index, SModel model) {
      SNode fieldDefinition = (SNode) enclosingNode;
      SPropertyOperations.assign(fieldDefinition, PROPS.showConstraints$opbl, true);
    }
  }

  private static final class PROPS {
    /*package*/ static final SProperty showConstraints$opbl = MetaAdapterFactory.getProperty(0xf06cb947e5a84701L, 0x9c0629d6e3bd07f9L, 0x21b0e207472b2391L, 0x372b1cbf957d392cL, "showConstraints");
  }
}
